---
name: Cleanup Pull Request Images

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  delete-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        repo:
          - embedded-devcontainer
          - embedded-devcontainer-cpp
          - embedded-devcontainer-rust
    steps:
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: nstwfdev/docker-registry-image-cleaner@727b7dba7dcdbc39aadb1b22f2c3a0a717fedbd3 # v1.0.1
        with:
          dockerhub_repo: ${{ matrix.repo }}
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          image_prefix: pr-${{ github.event.pull_request.number }}
  cleanup-cache:
    runs-on: ubuntu-latest
    permissions:
      # actions: write permission is required to delete the cache
      actions: write
    steps:
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - run: |
          gh extension install actions/gh-actions-cache

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          for cacheKey in $(gh actions-cache list -R "${GH_REPO}" -B "${BRANCH}" | cut -f 1)
          do
              gh actions-cache delete "${cacheKey}" -R "${GH_REPO}" -B "${BRANCH}" --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
