---
name: Pull Request Report

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  add-pr-report:
    permissions:
      contents: read
      checks: read
      pull-requests: write
      repository-projects: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      - uses: philips-software/pull-request-report-action@39e2f082490099021474c109cb207953221a8e47 # v0.1.5
        env:
          GITHUB_TOKEN: ${{ github.token }}
