---
name: Finalize Release

on:
  release:
    types: [published]

permissions: {}

jobs:
  comment-released-prs:
    name: Comment on released PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - uses: rdlf0/comment-released-prs-action@a81897eaea04a5faa8779d28607826ddb033321a # v3.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
